services:
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - ./docker/nginx/conf.dev.d:/etc/nginx/conf.d:ro
    ports:
      - 8000:80
    networks:
      - default

  db:
    image: mongo
    volumes:
      - ./docker/db/data:/var/lib/mongo
      - ./docker/db/db-init:/docker-entrypoint-initdb.d
    env_file:
      - ./database.env

  backend:
    build:
      target: runtime_dev
    ports:
      - 5678:5678
    depends_on:
      - db
    networks:
      - default

  start_dependencies:
    build: ./docker/start_dependencies
    depends_on:
      - backend
    command: db:27017 /var/run/python/uwsgi.sock
    volumes:
      - python_sock:/var/run/python
