# Generated by Django 5.2.2 on 2025-07-24 21:53

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessCase',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the illness case', null=True)),
                ('markup', models.JSONField(blank=True, help_text='Markup of the illness case', null=True)),
                ('age', models.IntegerField(blank=True, help_text='Age of the patient', null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='Sex of the patient', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='IllnessPicture',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(help_text='Picture of the illness case', upload_to='illness_cases/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('illness_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.illnesscase')),
            ],
        ),
        migrations.CreateModel(
            name='IllnessTag',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tag', max_length=255)),
                ('type', models.CharField(choices=[('Illness', 'Illness'), ('Organ', 'Organ'), ('OrganSystem', 'Organ System'), ('Institution', 'Institution')], default='Illness', help_text='Type of the tag', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.AddField(
            model_name='illnesscase',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags of the illness case', to='archive.illnesstag'),
        ),
    ]
